In [1]:
import torch 
import torch.nn as nn

In [147]:
rnn = nn.RNN(
    input_size=2,
    hidden_size=3,
    num_layers=2,
    bidirectional=True,
    batch_first=True
)

In [148]:
torch.manual_seed(1)

In [149]:
x = torch.rand((2, 3, 2))
x

tensor([[[0.7576, 0.2793],
         [0.4031, 0.7347],
         [0.0293, 0.7999]],

        [[0.3971, 0.7544],
         [0.5695, 0.4388],
         [0.6387, 0.5247]]])

In [150]:
a, b = rnn(x)
a.size(), b.size()

(torch.Size([2, 3, 6]), torch.Size([4, 2, 3]))

In [151]:
a, b

(tensor([[[ 0.2705, -0.4817, -0.4942,  0.5036,  0.2571,  0.2665],
          [ 0.0718, -0.6734, -0.5874,  0.3893,  0.2746,  0.1342],
          [ 0.1746, -0.8002, -0.3946,  0.3671,  0.0259, -0.2233]],
 
         [[ 0.3389, -0.5673, -0.3850,  0.3298,  0.2505,  0.2656],
          [ 0.0843, -0.6184, -0.6814,  0.4094,  0.2714,  0.2084],
          [ 0.1766, -0.8106, -0.3962,  0.5012,  0.0362, -0.3131]]],
        grad_fn=<TransposeBackward1>),
 tensor([[[ 0.3011, -0.3470,  0.7114],
          [ 0.4772, -0.3723,  0.7374]],
 
         [[-0.4692,  0.2368, -0.7825],
          [-0.5901,  0.5227, -0.6913]],
 
         [[ 0.1746, -0.8002, -0.3946],
          [ 0.1766, -0.8106, -0.3962]],
 
         [[ 0.5036,  0.2571,  0.2665],
          [ 0.3298,  0.2505,  0.2656]]], grad_fn=<StackBackward>))

In [96]:
b.transpose(0, 1)

tensor([[[ 0.0261,  0.2325,  0.4399, -0.4072,  0.3703],
         [ 0.0763,  0.0160, -0.7184,  0.0224,  0.7377]]],
       grad_fn=<TransposeBackward0>)

In [79]:
b.is_contiguous()

True